# Generated by Django 5.1.4 on 2024-12-05 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role_requirement'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='projects.project')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use_cases', to='core.requirement')),
            ],
        ),
    ]
