# Generated by Django 5.1.4 on 2024-12-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_role_requirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('project_manager', 'Project Manager'), ('developer', 'Developer'), ('system_designer', 'System Designer'), ('system_analyst', 'System Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
