# Generated by Django 5.1.4 on 2024-12-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False),
        ),
    ]
